pipeline {
    agent { 
        kubernetes {
            label 'python38'
        }
    }
    stages {
        stage('Check Python') {
            steps{
                script {
                    container('python38') {
                        sh """
                            python -V
                        """
                    }
                }
            }
        }
    }
}